[package]
name = "stateright"
version = "0.5.0"
authors = ["Jonathan Nadal <jon.nadal@gmail.com>"]
license = "MIT"
edition = "2018"

description = "A model checker for implementing distributed systems."
repository = "https://github.com/stateright/stateright"
readme = "README.md"
categories = ["algorithms", "concurrency", "development-tools", "network-programming", "simulation"]
keywords = ["actor", "distributed-systems", "model-checking", "paxos"]

[dependencies]
ahash = "0.3.2"
actix-files = "0.1"
actix-web = "1.0.9"
crossbeam-utils = "0.7.0"
dashmap = "3.2.2"
regex = "1.3.1"
serde = { version = "1.0.104", features = ["rc"] }
serde_derive = "1.0.104"
serde_json = "1.0.44"
id-set = "0.2.2"

[dev-dependencies]
clap = "2.33.0"
num_cpus = "1.11.1"
